public class hogehoge() {

    /* create user B */
    private void method2() {
        String str = 'test';
    }
      
    /* create user C */
    public void save() {
        String checkPrm = '';
        if (isCheck(checkPrm)) {
            //保存ロジック
        } else {
            //チェックNGのためメッセージ表示
        }
    }

    /* create user C */
    private boolean isCheck(String prm) {
        if (prm == 'normal') {
            return true;
        } else {
            return false;
        }
    }
}
